[default.files]
profile = "~/.profile"
starship = "~/.config/starship.toml"

[bash.files]
"bash/bashrc" = "~/.bashrc"
"bash/bash_logout" = "~/.bash_logout"

[zsh.files]
"zsh/zshenv" = "~/.zshenv"
"zsh/zshrc" = "~/.zshrc"

[vim.files]
"vim/vimrc" = "~/.vimrc"
"vim/ideavimrc" = "~/.ideavimrc"
